# Generated by Django 3.2.3 on 2023-01-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('don_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ably',
        ),
    ]
