# Generated by Django 3.2.3 on 2023-01-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_home', '0003_auto_20230130_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe24',
            name='service_key',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
