# Generated by Django 3.2.3 on 2023-01-31 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('don_home', '0004_cafe24_service_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AblySalesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateTimeField()),
                ('productOrderNumber', models.IntegerField()),
                ('orderNumber', models.IntegerField()),
                ('productName', models.CharField(max_length=150)),
                ('options', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('orderName', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('orderStatus', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AblyProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productNumber', models.IntegerField()),
                ('productName', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('discountPeriod', models.CharField(default='none', max_length=20)),
                ('discountPrice', models.CharField(max_length=50)),
                ('registrationDate', models.DateTimeField()),
                ('statusDisplay', models.CharField(max_length=10)),
                ('stock', models.CharField(max_length=10)),
                ('totalReview', models.IntegerField()),
                ('parcel', models.CharField(max_length=10)),
                ('returnShippingCost', models.IntegerField()),
                ('extraShippingCost', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
