# Generated by Django 3.2.3 on 2023-01-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_home', '0006_auto_20230131_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ablysalesinfo',
            name='orderNumber',
            field=models.CharField(max_length=50),
        ),
    ]
