# Generated by Django 3.2.3 on 2023-01-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_home', '0009_alter_ablyproductinfo_discountperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ablyproductinfo',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
