# Generated by Django 3.2.3 on 2023-01-31 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('don_home', '0011_testdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDB',
        ),
    ]
