# Generated by Django 3.2.3 on 2023-01-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_home', '0012_delete_testdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productNumber', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discountPrice', models.IntegerField()),
                ('basicShippingCost', models.IntegerField()),
                ('returnShippingCost', models.IntegerField()),
                ('exchangeShippingCost', models.IntegerField()),
                ('largeCategory', models.CharField(max_length=100)),
                ('smallCategory', models.CharField(max_length=100)),
                ('productRegistrationDate', models.DateField()),
                ('productModificationDate', models.DateField()),
                ('user', models.IntegerField()),
            ],
        ),
    ]
