# Generated by Django 3.2.3 on 2023-01-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_home', '0014_auto_20230201_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naverproductinfo',
            name='basicShippingCost',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='naverproductinfo',
            name='discountPrice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='naverproductinfo',
            name='exchangeShippingCost',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='naverproductinfo',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='naverproductinfo',
            name='returnShippingCost',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='naverproductinfo',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
