# Generated by Django 3.2.3 on 2023-01-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_home', '0015_auto_20230201_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverSalesPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleDate', models.CharField(max_length=100)),
                ('totalBuyer', models.IntegerField()),
                ('totalPayments', models.IntegerField()),
                ('price', models.IntegerField()),
                ('totalpaymentProduct', models.IntegerField()),
                ('basicShippingCost', models.IntegerField()),
                ('productCoupons', models.IntegerField()),
                ('numberRefunds', models.IntegerField()),
                ('refundAmount', models.IntegerField()),
                ('totalRefund', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
