# Generated by Django 3.2.3 on 2023-02-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('don_home', '0016_naversalesperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe24Cateory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_no', models.IntegerField()),
                ('category_depth', models.IntegerField()),
                ('parent_category_no', models.IntegerField()),
                ('category_name', models.CharField(max_length=50)),
                ('display_type', models.CharField(max_length=50)),
                ('large_catetgory', models.CharField(max_length=50)),
                ('mid_category', models.CharField(max_length=50)),
                ('small_category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('large_catetgory_no', models.IntegerField()),
                ('mid_category_no', models.IntegerField()),
                ('small_category_no', models.IntegerField()),
                ('sub_category_no', models.IntegerField()),
                ('root_category_no', models.IntegerField()),
                ('use_main', models.CharField(max_length=50)),
                ('display_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cafe24Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_no', models.IntegerField()),
                ('benefit_price', models.IntegerField()),
                ('coupon_type', models.CharField(max_length=100)),
                ('coupon_name', models.CharField(max_length=100)),
                ('created_date', models.CharField(max_length=100)),
                ('deleted', models.CharField(max_length=50)),
                ('benefit_text', models.CharField(max_length=100)),
                ('benefit_percentage', models.IntegerField()),
                ('issue_meneber_join', models.CharField(max_length=50)),
                ('issued_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cafe24Oprder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_no', models.IntegerField()),
                ('product_code', models.CharField(max_length=50)),
                ('benefit_price', models.IntegerField()),
                ('member_id', models.CharField(max_length=50)),
                ('member_email', models.CharField(max_length=100)),
                ('payment_method_name', models.CharField(max_length=100)),
                ('paid', models.CharField(max_length=50)),
                ('canceled', models.CharField(max_length=50)),
                ('order_date', models.CharField(max_length=100)),
                ('first_order', models.CharField(max_length=50)),
                ('order_from_modbil', models.CharField(max_length=50)),
                ('inital_order_amount', models.IntegerField()),
                ('actual_order_amount', models.IntegerField()),
                ('payment_amount', models.IntegerField()),
                ('order_place_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cafe24Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.IntegerField()),
                ('product_code', models.CharField(max_length=50)),
                ('categoty_no', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('price_excluding_tax', models.IntegerField()),
                ('price', models.IntegerField()),
                ('retail_price', models.IntegerField()),
                ('supply_price', models.IntegerField()),
                ('display', models.CharField(max_length=100)),
                ('selling', models.CharField(max_length=50)),
                ('product_condition', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField()),
                ('sold_out', models.CharField(max_length=50)),
            ],
        ),
    ]
