# Generated by Django 3.2.3 on 2023-02-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('don_home', '0019_auto_20230201_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe24category',
            old_name='large_catetgory',
            new_name='large_category',
        ),
    ]
